### ISSUE TITLE
feature-request: ORGiD SDK to support Goerli, Polygon, Gnosis Chains

### ISSUE THREAD

**Issue by dave-ok** [windingtree/org.id-cli#5]
### The problem: Depracation
The network chains currently supported by the ORGiD SDK are:
- Sokol xDAI Testnet
- Arbitrum Rinkeby Testnet
- Rinkeby Testnet (**To be deprecated**)
- Ropsten Testnet (**To be deprecated**)
As indicated above `Rinkeby` and `Ropsten` are to be deprecated soon.

### Feature Request
To forestall the deprecation of the chains above and increase the options of networks available, \
can some or all of the following chains be included among the supported networks?
- Goerli 
- Polygon 
- Gnosis Chains

Thanks!

**Comment by kostysh** [comment]
I think it will be quite easy to implement it for `Gnosis Chain` and, maybe `Goerli`, but I am not sure about the `Polygon`. 
We need to check if their `evm` has restrictions on the solidity compiler version. If not - we will be able to deploy contracts there without changes on the smart contract level. I need to discuss it with my team -  when it will be possible to pay attention on the `ORGiD` project.

**Comment by dave-ok** [comment]
This is very much appreciated. Thank you!

**Comment by kostysh** [comment]
version 3.1.0 is already supported Goerli, Gnosis and Polygon nets
